### ISSUE TITLE
1주차 추가 과제?

### ISSUE THREAD

**Issue by JSY8869** [JSY8869/OpenCV#2]
생각보다 너무 일찍 끝나서 추가로 더 해볼까 하는데 어떻게 생각하나요?
https://076923.github.io/posts/Python-opencv-5/
해당 블로그에서 5 ~ 10강정도 생각하고 있습니다.
2시간 안에 끝낼 수 있는 분량이라고 생각합니다.

**Comment by park-sohyeon** [comment]
예에엡<^^>

**Comment by JSY8869** [comment]
# [완료](https://github.com/JSY8869/OpenCV/tree/main/JSY8869)

**Comment by park-sohyeon** [comment]
## 5장

cv2.flip(src, 0) -> 그림좌우반전/ 1은 좌우반전, 0은 상하반전

## 6장
matrix = cv2.getRotationMatrix2D((중심점 X좌표, 중심점 Y좌표), 각도, 스케일)
여기서 중심점 - 튜플
스케일 - 확대 비율

cv2.warpAffine(원본 이미지, 배열, (결과 이미지 너비, 결과 이미지 높이))
아까 matrix에 따라 이미지 회전

## 7장
cv2.pyrUp(원본 이미지, 결과 이미지 크기, 픽셀 외삽법) - 확대
cv2.pyDown(원본 이미지, 결과 이미지 크기, 픽셀 외삽법) - 축소
외삽방식 - cv2.BORDER_DEFAULT사용
사실상 결과 이미지 크기랑 픽셀 외삽법 생략

## 8장
cv2.resize(원본 이미지, 결과 이미지 크기, 보간법) - 이미지크기 조절

만약 결과 이미지 크기 (0,0) - > fx, fy를 이용해 비율 조절(몇 배)
결과 이미지 튜플
보간법은 cv2.INTER_LINEAR,cv2.INTER_CUBIC - 확대할 때 가장 많이 사용
축소 - cv2.INTER_AREA

## 9강
이미지 복제 후 
dst = src[100:600, 200:700] -> 잘라낸다.(list형식)
dst[0:500, 0:500] = roi -> 붙여넣기

## 10강(흑백)

cv2.cvtcolor(원본 이미지, 색상 변환 코드)
여기서 BGR = RGB
